// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package docs

import (
	"errors"
	"fmt"
	"strings"

	"github.com/elastic/elastic-package/internal/docs"
	"github.com/elastic/elastic-package/internal/llmagent/ui"
	"github.com/elastic/elastic-package/internal/tui"
)

// getUserAction prompts the user for their next action
func (d *DocumentationAgent) getUserAction() (string, error) {
	selectPrompt := tui.NewSelect("What would you like to do?", []string{
		"Accept and finalize",
		"Request changes",
		"Cancel",
	}, "Accept and finalize")

	var action string
	err := tui.AskOne(selectPrompt, &action)
	if err != nil {
		return "", fmt.Errorf("prompt failed: %w", err)
	}

	return action, nil
}

// displayReadmeIfUpdated shows documentation content if it was updated
func (d *DocumentationAgent) displayReadmeIfUpdated() bool {
	readmeUpdated, _ := d.isReadmeUpdated()
	if !readmeUpdated {
		fmt.Printf("\n⚠️  %s file not updated\n", d.targetDocFile)
		return false
	}

	sourceContent, err := d.readCurrentReadme()
	if err != nil || sourceContent == "" {
		fmt.Printf("\n⚠️  %s file exists but could not be read or is empty\n", d.targetDocFile)
		return false
	}

	// Try to render the content
	renderedContent, shouldBeRendered, err := docs.GenerateReadme(d.targetDocFile, d.packageRoot)
	if err != nil || !shouldBeRendered {
		fmt.Printf("\n⚠️  The generated %s could not be rendered.\n", d.targetDocFile)
		fmt.Println("It's recommended that you do not accept this version (ask for revisions or cancel).")
		return true
	}

	// Show the processed/rendered content
	processedContentStr := string(renderedContent)
	fmt.Printf("📊 Processed %s stats: %d characters, %d lines\n", d.targetDocFile, len(processedContentStr), strings.Count(processedContentStr, "\n")+1)

	// Try to open in browser first
	if ui.TryBrowserPreview(processedContentStr) {
		fmt.Println("🌐 Opening documentation preview in your web browser...")
		fmt.Println("💡 Return here to accept or request changes.")
	} else {
		// Fallback to terminal display if browser preview fails
		title := fmt.Sprintf("📄 Processed %s (as generated by elastic-package build)", d.targetDocFile)
		if err := tui.ShowContent(title, processedContentStr); err != nil {
			// Fallback to simple print if viewer fails
			fmt.Printf("\n%s:\n", title)
			fmt.Println(strings.Repeat("=", 70))
			fmt.Println(processedContentStr)
			fmt.Println(strings.Repeat("=", 70))
		}
	}

	return true
}

// handleReadmeUpdate checks if documentation file was updated and reports the result
func (d *DocumentationAgent) handleReadmeUpdate() (bool, error) {
	readmeUpdated, _ := d.isReadmeUpdated()
	if !readmeUpdated {
		return false, nil
	}

	content, err := d.readCurrentReadme()
	if err != nil || content == "" {
		return false, err
	}

	fmt.Printf("✅ Documentation update completed! (%d characters written to %s)\n", len(content), d.targetDocFile)
	return true, nil
}

// handleInteractiveError handles error responses in interactive mode
func (d *DocumentationAgent) handleInteractiveError() (string, bool, error) {
	fmt.Println("\n❌ Error detected in LLM response.")

	errorPrompt := tui.NewSelect("What would you like to do?", []string{
		"Try again",
		"Exit",
	}, "Try again")

	var errorAction string
	err := tui.AskOne(errorPrompt, &errorAction)
	if err != nil {
		return "", false, fmt.Errorf("prompt failed: %w", err)
	}

	if errorAction == "Exit" {
		fmt.Println("⚠️  Exiting due to LLM error.")
		return "", false, nil
	}

	// Continue with retry prompt
	promptCtx := d.createPromptContext(d.manifest, "The previous attempt encountered an error. Please try a different approach to analyze the package and create/update the documentation.")
	prompt := d.buildPrompt(PromptTypeRevision, promptCtx)
	return prompt, true, nil
}

// handleUserAction processes the user's chosen action
func (d *DocumentationAgent) handleUserAction(action string, readmeUpdated bool) (string, bool, bool, error) {
	switch action {
	case "Accept and finalize":
		return d.handleAcceptAction(readmeUpdated)
	case "Request changes":
		return d.handleRequestChanges()
	case "Cancel":
		fmt.Println("❌ Documentation update cancelled.")
		d.restoreOriginalReadme()
		return "", false, true, nil
	default:
		return "", false, false, fmt.Errorf("unknown action: %s", action)
	}
}

// handleAcceptAction handles the "Accept and finalize" action
func (d *DocumentationAgent) handleAcceptAction(readmeUpdated bool) (string, bool, bool, error) {
	if readmeUpdated {
		// Validate preserved sections if we had original content
		if d.originalReadmeContent != nil {
			if newContent, err := d.readCurrentReadme(); err == nil {
				preserved := d.arePreservedSectionsKept(*d.originalReadmeContent, newContent)
				if !preserved {
					fmt.Println("⚠️  Warning: Some human-edited sections may not have been preserved")
					fmt.Println("   Please review the documentation to ensure important content wasn't lost.")
				}
			}
		}

		fmt.Println("✅ Documentation update completed!")
		return "", false, true, nil
	}

	// Documentation file wasn't updated - ask user what to do
	continuePrompt := tui.NewSelect(fmt.Sprintf("%s file wasn't updated. What would you like to do?", d.targetDocFile), []string{
		"Try again",
		"Exit anyway",
	}, "Try again")

	var continueChoice string
	err := tui.AskOne(continuePrompt, &continueChoice)
	if err != nil {
		return "", false, false, fmt.Errorf("prompt failed: %w", err)
	}

	if continueChoice == "Exit anyway" {
		fmt.Printf("⚠️  Exiting without creating %s file.\n", d.targetDocFile)
		d.restoreOriginalReadme()
		return "", false, true, nil
	}

	fmt.Printf("🔄 Trying again to create %s...\n", d.targetDocFile)
	promptCtx := d.createPromptContext(d.manifest, fmt.Sprintf("You haven't written a %s file yet. Please write the %s file in the _dev/build/docs/ directory based on your analysis.", d.targetDocFile, d.targetDocFile))
	newPrompt := d.buildPrompt(PromptTypeRevision, promptCtx)
	return newPrompt, true, false, nil
}

// handleRequestChanges handles the "Request changes" action
func (d *DocumentationAgent) handleRequestChanges() (string, bool, bool, error) {
	changes, err := tui.AskTextArea("What changes would you like to make to the documentation?")
	if err != nil {
		// Check if user cancelled
		if errors.Is(err, tui.ErrCancelled) {
			fmt.Println("⚠️  Changes request cancelled.")
			return "", true, false, nil // Continue the loop
		}
		return "", false, false, fmt.Errorf("prompt failed: %w", err)
	}

	// Check if no changes were provided
	if strings.TrimSpace(changes) == "" {
		fmt.Println("⚠️  No changes specified. Please try again.")
		return "", true, false, nil // Continue the loop
	}
	promptCtx := d.createPromptContext(d.manifest, changes)
	newPrompt := d.buildPrompt(PromptTypeRevision, promptCtx)
	return newPrompt, true, false, nil
}
